singleQuote: true
semi: false
printWidth: 80
trailingComma: none
plugins:
  - 'prettier-plugin-tailwindcss'
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
