singleQuote: true
semi: false
printWidth: 80
trailingComma: none
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
