singleQuote: true
semi: false
printWidth: 80
trailingComma: none
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '^[a-zA-Z0-9]'
  - '^@ui'
  - '^@libs'
  - '^@utils'
  - '^@database'
  - '^@models'
  - '^@repositories'
  - '^@services'
  - '^@controllers'
  - '^@ipc'
  - '^@main/shared'
  - '^@shared'
  - '^[./]'
  - '^[../]'
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
