singleQuote: true
semi: false
printWidth: 100
trailingComma: none
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
tailwindFunctions:
  - clsx
  - cva
tailwindPreserveDuplicates: true
proseWrap: 'always'
importOrder:
  - '^[a-zA-Z0-9]'
  - '^react'
  - '^@react'
  - '^@app'
  - '^@pages'
  - '^@widgets'
  - '^@features'
  - '^@entities'
  - '^@shared'
  - '^[./]'
  - '^[../]'
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
